length=float(input("enter a length:"))
breadth=float(input("enter a breadth:"))
cr=2*(length+breadth)
print("="*50)
print("\t lenght={}".format(length))
print("\t breadth={}".format(breadth))
print("\t circumference={}".format(cr))
print("="*50)
