print('enter a first value:')
s1=input()
print('enter a second value:')
s2=input()
a=float(s1)
b=float(s2)
c=a*b
print("="*50)
print("val of a={}".format(a))
print("val of b={}".format(b))
print("sum={}".format(c))
print("="*50)