import sys
eno=int(input("enter employee number:"))
ename=input("enter a employee name:")
bsal=float(input("enter employee basic salary:"))
if(bsal<=0):
    print("{} is invalid salary and dont work".format(bsal))
    sys.exit()
elif(0<bsal<=10000):
    da=bsal*(10/100)
    ta=bsal*(8/100)
    hra=bsal*(6/100)
    ma=bsal*(1/100)
    lic=bsal*(1/100)
    gpf=bsal*(1.5/100)
elif(bsal>10000):
    da = bsal * (20 / 100)
    ta = bsal *(10 / 100)
    hra = bsal * (8 / 100)
    ma = bsal * (1/100)
    lic = bsal * (1 / 100)
    gpf = bsal * (1.5 / 100)
netsal=(bsal+da+ta+ma+hra)-(lic+gpf)
print("==================================")
print("pay slip of an employee")
print("=====================")
print("\t employee number:{}".format(eno))
print("\t empolyee name:{}".format(ename))
print("\t basic salary:{}".format(bsal))
print("\t employee da:{}".format(da))
print("\t employee ta:{}".format(ta))
print("\t employee hra:{}".format(hra))
print("\t employee ma:{}".format(ma))
print("deductions")
print("\t employee lic:{}".format(lic))
print("\t employee gpe:{}".format(gpf))
print("\t emp net salary:{}".format(netsal))
print("=====================")